// Code generated by scripts/generate-schema-identifiers.mjs; DO NOT EDIT.

package executor

const (
	ComputationExecutionSchema = "overcenter-computation-execution-v1"
	ProcessSpecSchema = "overcenter-process-spec-v1"
	ComputationEvidenceSchema = "overcenter-computation-attempt-evidence-v1"
	ExecutorCommandSchema = "overcenter-executor-command-v1"
	ExecutorHelloSchema = "overcenter-executor-hello-v1"
)
